language: ruby
rvm:
- 2.6.9
- 2.7.5
before_install: gem install bundler -v 1.13.0
after_script: bundle exec codeclimate-test-reporter
cache: bundler
gemfile:
  - gemfiles/activesupport_6.0.gemfile
  - gemfiles/activesupport_6.1.gemfile
