language: ruby
rvm:
- 2.6.9
- 2.7.5
before_install: gem install bundler -v 1.13.0
after_script: bundle exec codeclimate-test-reporter
cache: bundler
env:
  matrix:
    - TEST_RAILS_VERSION=6.1
    - TEST_RAILS_VERSION=6.0
